---
title: "Untitled"
author: "Shayla Nikzad"
date: "9/29/2020"
output: html_document
---
## Setup
```{r setup, include = F}
knitr::opts_chunk$set(warning = F, message = F)
```

## Loading Libraries
```{r}
library(tidyverse)
library(plotly)
library(sf)
library(tigris)
library(leaflet)
library(censusapi)

Sys.setenv(CENSUS_KEY="c8aa67e4086b4b5ce3a8717f59faa9a28f611dab")
```

## Reading + Saving Files 
```{r}

#reading from the web 

health_full <- read_csv("https://chronicdata.cdc.gov/api/views/6vp6-wxuq/rows.csv?accessType=DOWNLOAD")

health_ca <- filter(health_full, StateAbbr == "Ca")

write_csv(health_ca, "health_ca.csv")

#reading from directory 

pge_19_q1_elec <- read_csv("PGE_2019_Q1_ElectricUsageByZip.csv")
```

# Loops
```{r}

year <- 2019 
quarters <- 1:4 
type <- "Electric"

pge_19_elec <- NULL


for(quarter in quarters) {

  filename <- paste0("PGE_", year, "_Q", quarter, "_", type, "UsageByZip.csv")

  print(filename)

  temp <- read_csv(filename) 

  pge_19_elec <- rbind(pge_19_elec, temp)
  
  saveRDS(pge_19_elec, "pge_19_elec.rds")
  
}

```

## Manipulating Data 
```{r}

pge_filter <- filter(pge_19_elec, CUSTOMERCLASS %in% c("Elec- Residential","Elec- Commercial"))

names(pge_filter)

head(pge_filter)


#removing some data that is not important with !c
pge_select <-
  select(
    pge_filter,
    !c(YEAR, COMBINED, AVERAGEKWH)
  )

table(pge_select$COMBINED)


#some vague notion that we are collapsing some data here 
pge_group <-
  group_by(
    pge_select,
    MONTH,
    CUSTOMERCLASS
  )

#making tidy data 
pge_summarize <-
  summarize(
    pge_group,
    TOTALKWH = 
      sum(
        TOTALKWH, 
        na.rm = T
      )
  )

#convert to a more conventional data format 
pge_wide <-
  pivot_wider(
    pge_summarize,
    names_from = CUSTOMERCLASS,
    values_from = TOTALKWH
  )

pge_wide

#convert it back 
pge_tidy <-
  pivot_longer(
    pge_wide,
    c("Elec- Commercial", "Elec- Residential"),
    names_to = "CUSTOMERCLASS",
    values_to = "TOTALKWH"
  )


#Adding total customers 
pge_summarize <-
  summarize(
  pge_group,
  TOTALKWH = 
    sum(
      TOTALKWH, 
      na.rm = T
    ),
  TOTALCUSTOMERS =
    sum(
      TOTALCUSTOMERS,
      na.rm = T
    )
  )

#mutate is doing an opperation on this data 
pge_mutate <-
  mutate(
    pge_summarize,
    AVERAGEKWH =
      TOTALKWH/TOTALCUSTOMERS
  )


#recoding using the pipe 
pge_final <-
  pge_19_elec %>% 
  filter(
    CUSTOMERCLASS %in% 
      c(
        "Elec- Residential",
        "Elec- Commercial"
      )
  ) %>% 
  select(
    !c(YEAR, COMBINED, AVERAGEKWH)
  ) %>% 
  group_by(MONTH, CUSTOMERCLASS) %>% 
  summarize(
    TOTALKWH = 
      sum(
        TOTALKWH, 
        na.rm = T
      ),
    TOTALCUSTOMERS =
      sum(
        TOTALCUSTOMERS,
        na.rm = T
      )
  ) %>% 
  mutate(
    AVERAGEKWH =
      TOTALKWH/TOTALCUSTOMERS
  )

pge_final

#ctrl+shift+M can help to write the pipe 

```


## Plotting 
```{r}
library(tidyverse)
library(plotly)

pge_chart <-
  pge_final %>% 
  ggplot() +
  geom_bar(
    aes(
      x = MONTH %>% factor(),
      y = TOTALKWH,
      fill = CUSTOMERCLASS
    ),
    stat = "identity",
    position = "stack"
  ) +
  labs(
    x = "Month",
    y = "kWh",
    title = "PG&E Territory Monthly Electricity Usage, 2019",
    fill = "Electricity Type"
  )

pge_chart

#make it interactive 

pge_chart %>% ggplotly()

```
## Geospatial Data 

```{r}

ca_counties <- counties("CA", cb = T, progress_bar = F)

st_crs(ca_counties)

#mapping 
ggplot(ca_counties) + geom_sf()

#leaflet stuff 
leaflet() %>% 
  addTiles() %>% 
  addPolygons(
    data = ca_counties %>% 
      st_transform(4326)
  ) %>%
  addMarkers(
    data = ca_counties %>% 
      st_centroid() %>%
      st_transform(4326)
  )

#get just the bay area counties 
bay_county_names <-
  c(
    "Alameda",
    "Contra Costa",
    "Marin",
    "Napa",
    "San Francisco",
    "San Mateo",
    "Santa Clara",
    "Solano",
    "Sonoma"
  )

bay_counties <-
  counties("CA", cb = T, progress_bar = F) %>%
  filter(NAME %in% bay_county_names)

ggplot(bay_counties) + geom_sf()


#loading cities in a specific state 
ca_cities <- places("CA", cb = T, progress_bar = FALSE)
bay_cities <- ca_cities[bay_counties, ]


#cutting out border towns 

bay_cities_within <-
  ca_cities %>% 
  st_centroid() %>% 
  .[bay_counties, ] %>% 
  st_set_geometry(NULL) %>% 
  left_join(ca_cities %>% select(GEOID)) %>% 
  st_as_sf()


#making another leaflet map 
leaflet() %>% 
  addTiles() %>% 
  addPolygons(
    data = bay_counties %>% 
      st_transform(4326),
    fill = F,
    weight = 2
  ) %>%
  addPolygons(
    data = bay_cities %>% 
      filter(!GEOID %in% bay_cities_within$GEOID) %>% 
      st_transform(4326),
    color = "red"
  ) %>% 
  addPolygons(
    data = bay_cities_within %>% 
      st_transform(4326),
    color = "green"
  )

```


